# Generated by Django 3.2.10 on 2022-07-12 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_alter_about_about_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='main_home'),
            preserve_default=False,
        ),
    ]
