# Generated by Django 3.2.10 on 2022-07-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0016_auto_20220712_1214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='RecentWork',
        ),
    ]
