# Generated by Django 3.2.10 on 2022-07-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0017_rename_projects_recentwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Email', models.EmailField(max_length=254)),
                ('Subjects', models.CharField(max_length=250)),
                ('Messages', models.TextField(max_length=2000)),
            ],
        ),
    ]
