# Generated by Django 3.2.10 on 2022-07-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0021_auto_20220713_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=150)),
                ('Enquiry', models.CharField(max_length=300)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
