# Generated by Django 3.2.10 on 2022-07-13 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0023_auto_20220713_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='Email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='Messages',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='Subject',
            field=models.CharField(default='', max_length=400),
        ),
    ]
