# Generated by Django 3.2.10 on 2022-07-13 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0024_auto_20220713_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='fullname',
            new_name='Full_Name',
        ),
    ]
