# Generated by Django 3.2.10 on 2022-07-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0025_rename_fullname_mymodel_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('skill', models.TextField(blank=True, max_length=330, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='portfolio')),
            ],
        ),
    ]
