# Generated by Django 3.2.10 on 2022-08-07 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0027_rename_allworks_allwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='skills_logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='about'),
            preserve_default=False,
        ),
    ]
