# Generated by Django 3.2.10 on 2022-08-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0028_about_skills_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logos', models.ImageField(upload_to='main_home')),
                ('logo_name', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='skills_logo',
        ),
    ]
