# Generated by Django 3.2.10 on 2022-08-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0029_auto_20220807_1948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill_Languages',
            new_name='Skill_Language',
        ),
    ]
