# Generated by Django 3.2.10 on 2022-08-07 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0030_rename_skill_languages_skill_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='my_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='main_home'),
            preserve_default=False,
        ),
    ]
