# Generated by Django 3.2.10 on 2022-08-08 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0032_auto_20220807_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='twitter',
            new_name='whatsapp',
        ),
    ]
